spring:
  datasource:
    shanyou:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.37.101.18:3306/shanyou?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: shanyou
    yuemenu:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.37.101.18:3306/yuemenu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: shanyou
mybatis:
  #  扫描xml文件
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.mapper.mapper: debug
  config: classpath:logback-dev-spring.xml